app = "betdota2-python"
primary_region = "mia"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8081"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
